// Auto-generated by Supabase CLI. Do not edit manually.
// Run: npx supabase gen types typescript --project-id <id> > types/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      doctors: {
        Row: {
          id: string
          name: string
          slug: string
          specialty: string
          bio: string | null
          education: string[]
          certifications: string[]
          photo_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['doctors']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['doctors']['Insert']>
      }
      doctor_schedules: {
        Row: {
          id: string
          doctor_id: string
          day_of_week: number
          start_time: string
          end_time: string
          slot_duration_mins: number
          is_active: boolean
        }
        Insert: Omit<Database['public']['Tables']['doctor_schedules']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['doctor_schedules']['Insert']>
      }
      services: {
        Row: {
          id: string
          name: string
          slug: string
          category: string
          short_desc: string | null
          description: string | null
          benefits: string[]
          price_min: number | null
          price_max: number | null
          duration_mins: number | null
          icon_name: string | null
          is_active: boolean
          sort_order: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['services']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['services']['Insert']>
      }
      promos: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          promo_code: string | null
          discount_type: string
          discount_value: number | null
          original_price: number | null
          promo_price: number | null
          start_date: string
          end_date: string
          max_claims: number | null
          current_claims: number
          eligibility: string
          image_url: string | null
          terms: string[]
          is_featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['promos']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['promos']['Insert']>
      }
      articles: {
        Row: {
          id: string
          title: string
          slug: string
          excerpt: string | null
          content: string | null
          category: string
          thumbnail_url: string | null
          author: string
          read_time_mins: number | null
          is_featured: boolean
          is_published: boolean
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['articles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['articles']['Insert']>
      }
      bookings: {
        Row: {
          id: string
          booking_code: string
          patient_name: string
          patient_phone: string
          patient_email: string | null
          patient_notes: string | null
          service_id: string | null
          doctor_id: string | null
          booking_date: string
          booking_time: string
          status: string
          admin_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['bookings']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['bookings']['Insert']>
      }
      contact_messages: {
        Row: {
          id: string
          name: string
          phone: string | null
          email: string
          subject: string | null
          message: string
          is_read: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['contact_messages']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['contact_messages']['Insert']>
      }
    }
    Views: {
      promos_with_status: {
        Row: Database['public']['Tables']['promos']['Row'] & {
          status: 'aktif' | 'member' | 'berakhir'
        }
      }
    }
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
